### ISSUE TITLE
Automated functional tests

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#13]
Investigate how possible/feasible it is for us to automate some of our functional testing. Can we automate some gameplay tests?

This might be a good start: http://funcunit.com/.

**Comment by secretrobotron** [comment]
I spoke with the lead of jQueryUI last week, and he had some suggestions which I wrote down for this problem exactly. Instead of Selenium, users log on to a system and basically volunteer their computer to do some testing, I believe. It was a Mozilla-backed project for a while. I'll find out more when I have my other laptop back.

Ah! Here it is. http://swarm.jquery.org/
