### ISSUE TITLE
Space / clock interaction story is confused

### ISSUE THREAD

**Issue by dmose** [gladiusjs/gladius-core#205]
Some of the issues here are that 
1. right now, it's possible to unit test the version of the Space constructor that takes a clock argument, but not actually access and use it from the engine.
2. new engine.simulation.Space() creates a space with the simulation clock, which doesn't appear to be easily testible, and for code maintainers, it can be confusing that this happens in the engine.js file by binding the Space code.  Some naming rearrangement seems likely to help here.

It may be that the simplest thing to do is simply write user stories about the space / clock interactions, and then it will become clearer how to frame the APIs.

**Comment by modeswitch** [comment]
1. We should expose the primitive Space constructor on the engine so that the user can pass whatever clock they choose.
2. Space should be moved out of the simulation object since not all spaces are simulation spaces. We should also rename the bound Space to SimulationSpace and create a new RealtimeSpace that's bound to the realtime system clock.

**Comment by modeswitch** [comment]
Fixes merged.
