### ISSUE TITLE
Resource manager/loader

### ISSUE THREAD

**Issue by modeswitch** [gladiusjs/gladius-core#6]
We need a resource manager to manage game assets like models, textures, and sounds.
- The engine should get a Cache instance when it is constructed.

``` javascript
engine.cache = new Cache();
```
- The cache instance should have a method get() for fetching content into the cache. Get() should accept a pair of callbacks to be invoked when the content is available in the cache, or if there is an error. Callbacks for onComplete and onError are invoked once per source, while the callback for onAllComplete is invoked once for all completed sources. 

``` javascript
engine.cache.get({
    content: [
        {
             url: [ 'http://...', ... ],            // multiple URLs specify alternate sources
             name: 'myContent'             
        }
    ],
    onComplete: function( content ) {
        ...
    },
    onAllComplete: function( content ) {
        ...
    },
    onError: function( source, error ) {
        ...
    }
});
```
- The cache should do all loading/processing for content in worker threads.
- The cache should keep track of interesting HTTP headers for its entries, such as Content-Type, or Expires.
- The cache instance should have a method find() for finding pre-cached content by name or url. Should return the content if it is cached, or null.

``` javascript
var content = engine.cache.find({
    name: ....,
    url: ...
});
```
- The cache instance should have a method clear() to unload cached content. If no options are given, the entire cache should be cleared.

``` javascript
engine.cache.clear({
    name: ...
    url: ...
});
```
- It might make sense to get a separate context for different parts of the client application so that assets can be fetched and cleared in batches.

``` javascript
var level1Cache = new engine.cache.Context();
var level2Cache = new engine.cache.Context();
level1Cache.get( ... );    // Pre-load a bunch of stuff for level 1
level2Cache.get( ... );
...
level1Cache.clear();      // This should clear out all the cached assets for level1, 
                                     // but things cached for level2 are not cleared.
```

@diogogmt will work on this.

This might be useful to look at: https://github.com/jussi-kalliokoski/html5Preloader.js

One question remaining is whether there is enough information provided to the API in get() so that the cache can know to use browser functionality to load sound, images, and video (for example).

Stories and tasks for this issue are [here](https://www.pivotaltracker.com/projects/373719).

**Comment by diogogmt** [comment]
An overview of what I understood about the resource manager/loader:

The Cache would receive a list of the resources the game would use and cache them on the browser.
The Cache object would also keep a track of all the resources, giving the user the ability to manipulate them during the game(get and delete)

Wouldn't be interest to have an option for just setting the resources on the Cache, but not loading them on the browser? For example:

``` javascript

level10Cache.set( ... );

```

Would set all the resources to be loaded on level 10, but wouldn't load them until

``` javascript

level10Cache.get( ... );

```

So instead of caching all the resources at the beginning of the game, the user could just set the path of the resources, and during the game manage when to get and when to clear them.

### Loading the resources:

I had thought that the resource could be load in a webworker thread. So the main page would send the path of the resource and then the thread would load it into the browser. 
However, I found that a webworker thread can't access the DOM, so how would the loading process happen?
For example:

``` javascript
// worker.js
vid = document.createElement('video');
or    
vid = new Video();
```

is not possible.

**Comment by secretrobotron** [comment]
RE Workers: This is mostly true. We can't create DOM objects right now, although it would be super fun to push for that in spec-land. We can do a bit of this work though, since you can send ImageData across the wire in a message without too much trouble (accelerated too, thanks for Firefox 5+). So, it should be possible to load data, do a bit of parsing (CubicVR workers can construct mesh arrays, etc.), and then message it over to the main thread. We just need proxy objects to take care of contextualizing this data.

I think it'd be good to set up a test to see how much pressure we can put on a system that loads data in a worker where possible (perhaps using data-uri). I'm not sure we'd win a lot though, since the parsing still has to happen in main thread, and the browser already does async net requests.

**Comment by diogogmt** [comment]
I did other changes to the module
Here is the branch with the changes
https://github.com/diogogmt/gladius/tree/t006

### Files changed:

```
src/gladius-src.js
src/core/Cache.js
test/index.html
test/core/Cache.js
examples/cache/index.html
```

I created a simple qunit test and an example demonstrating the module usage
